# Generated by Django 6.0.4 on 2026-09-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_alter_empleadocompetenciaasignada_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluaciondet',
            unique_together={('id_evaluacion', 'id_competencia', 'id_empleado', 'tipo')},
        ),
    ]
