# Generated by Django 6.0.4 on 2026-09-18 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_alter_evaluaciondet_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='clasificacionporempleado',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='clasificacionporpuesto',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='empleadocompetenciaasignada',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='evaluacioncomentario',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='evaluaciondet',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.empresa'),
        ),
    ]
