# Generated by Django 6.0.4 on 2026-09-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_empresa_clasificacionporempleado_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.IntegerField(verbose_name='ID Empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'id_empleado')},
        ),
    ]
