# Generated by Django 6.0.4 on 2026-09-19 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_empleado_id_alter_empleado_id_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadocompetenciaasignada',
            name='id_competencia',
            field=models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.CASCADE, to='rh.competencia'),
        ),
        migrations.AlterField(
            model_name='empleadocompetenciaasignada',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='competencias_asignadas', to='rh.empleado'),
        ),
        migrations.AlterField(
            model_name='evaluacioncomentario',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='rh.empleado'),
        ),
        migrations.AlterField(
            model_name='evaluacioncomentario',
            name='id_evaluacion',
            field=models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.CASCADE, to='rh.evaluacion'),
        ),
        migrations.AlterField(
            model_name='evaluaciondet',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='rh.empleado'),
        ),
        migrations.AlterField(
            model_name='tokenaccesoevaluacion',
            name='empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='rh.empleado'),
        ),
    ]
