# Generated by Django 6.0.4 on 2026-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_alter_empleadocompetenciaasignada_id_competencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': True, 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='puesto',
            options={'managed': True, 'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_departamento',
            field=models.IntegerField(verbose_name='ID Departamento (Local)'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='id_puesto',
            field=models.IntegerField(verbose_name='ID Puesto (Local)'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('empresa', 'id_departamento')},
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('empresa', 'id_puesto')},
        ),
    ]
