# Generated by Django 6.0.4 on 2026-09-21 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_alter_departamento_options_alter_puesto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadocompetenciaasignada',
            name='id_competencia',
            field=models.ForeignKey(db_column='id_competencia_id', on_delete=django.db.models.deletion.CASCADE, to='rh.competencia'),
        ),
    ]
