# Generated by Django 6.0.4 on 2026-09-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_alter_empleadocompetenciaasignada_id_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadocompetenciaasignada',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='competencias_asignadas', to='rh.empleado'),
        ),
    ]
