# Generated by Django 6.0.4 on 2026-09-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_alter_empleadocompetenciaasignada_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaccesoevaluacion',
            name='empleado',
            field=models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, to='rh.empleado'),
        ),
    ]
