# Generated by Django 6.0.4 on 2026-10-09 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0030_alter_tokenaccesoevaluacion_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': True, 'ordering': ['id_departamento'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'ordering': ['id_empleado']},
        ),
        migrations.AlterModelOptions(
            name='puesto',
            options={'managed': True, 'ordering': ['id_puesto'], 'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AlterField(
            model_name='evaluacioncomentario',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado_id', on_delete=django.db.models.deletion.CASCADE, to='rh.empleado'),
        ),
        migrations.AlterField(
            model_name='evaluacioncomentario',
            name='id_evaluacion',
            field=models.ForeignKey(db_column='id_evaluacion_id', on_delete=django.db.models.deletion.CASCADE, to='rh.evaluacion'),
        ),
    ]
