# Generated by Django 6.0.4 on 2026-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pivot_Dinamico',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Reporte')),
                ('slug', models.SlugField(help_text='Identificador para la URL (ej. inventario-pivot)', max_length=150, unique=True)),
                ('query_sql', models.TextField(help_text='Escribe la consulta SQL pura que alimentará los datos.', verbose_name='Consulta SQL (SELECT)')),
                ('configuracion_pivot', models.JSONField(blank=True, default=dict, help_text='JSON con la estructura de fields de DevExtreme (row, column, data, area, format).', verbose_name='Configuración DevExtreme (Campos, Filas, Columnas)')),
                ('icono', models.CharField(default='bar_chart', max_length=50, verbose_name='Icono de Material Symbols')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden en el Menú')),
            ],
            options={
                'verbose_name': 'Reporte Dinámico',
                'verbose_name_plural': 'Reportes Dinámicos',
                'db_table': 'rep_pivot_dinamico',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
