# Generated by Django 6.0.4 on 2026-10-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPivotUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plantilla', models.CharField(max_length=150)),
                ('configuracion_pivot', models.JSONField(help_text='Estado completo de DevExtreme obtenible con state()')),
                ('es_default', models.BooleanField(default=False)),
                ('fecha_inicio_macro', models.CharField(default='-3m', max_length=20)),
                ('fecha_fin_macro', models.CharField(default='m', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('reporte_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='reportes.pivot_dinamico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_pivot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rep_plantilla_pivot_usuario',
                'unique_together': {('reporte_base', 'usuario', 'nombre_plantilla')},
            },
        ),
    ]
