# Generated by Django 6.0.4 on 2026-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_plantillapivotusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivot_dinamico',
            name='fecha_fin_macro',
            field=models.CharField(default='m', help_text='Ejemplo: m, a, Hoy', max_length=20, verbose_name='Macro Fecha Final Default'),
        ),
        migrations.AddField(
            model_name='pivot_dinamico',
            name='fecha_inicio_macro',
            field=models.CharField(default='-3m', help_text='Ejemplo: -3m, A1, M, Hoy', max_length=20, verbose_name='Macro Fecha Inicial Default'),
        ),
        migrations.AlterField(
            model_name='plantillapivotusuario',
            name='fecha_fin_macro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Macro Fecha Final Personalizada'),
        ),
        migrations.AlterField(
            model_name='plantillapivotusuario',
            name='fecha_inicio_macro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Macro Fecha Inicial Personalizada'),
        ),
    ]
